# Generated by Django 5.2.3 on 2025-06-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='descricao',
            field=models.CharField(default='descrição do produto', max_length=100),
        ),
    ]
